services:
  neo4j:
    image: neo4j:5-community
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/taskatlas
    volumes:
      - task-atlas-neo4j:/data

volumes:
  task-atlas-neo4j:
